CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    Bestellnummer INT NOT NULL,
    Bestelldatum TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(50) NOT NULL,
    Preis DECIMAL(10, 2) NOT NULL
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS Liefertermin DATE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS Zahlungsart VARCHAR(50) NOT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS userID INT NOT NULL REFERENCES users(id);